# Generated by Codex on 2026-03-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insight",
            name="metric_snapshot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_insights",
                to="metrics.metricsnapshot",
            ),
        ),
    ]
