# Generated by Codex on 2026-03-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_insight_metric_snapshot"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("total_spend", models.FloatField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_impressions", models.IntegerField(default=0)),
                ("avg_ctr", models.FloatField(default=0)),
                ("avg_cpc", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["integration", "date"], name="analytics_m_integra_4f6f58_idx")],
            },
        ),
    ]
