# Generated by Codex on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_create_metricsaggregate"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(fields=["integration", "created_at"], name="analytics_i_integra_c9f1c7_idx"),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(fields=["severity", "type"], name="analytics_i_severi_92cb53_idx"),
        ),
    ]
