# Generated by Django 5.0 on 2026-02-20 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='metrics.metricsnapshot')),
            ],
        ),
    ]
