# Generated by Codex on 2026-03-11

from django.db import migrations


def forwards(apps, schema_editor):
    AlertInsight = apps.get_model("alerts", "Insight")
    AnalyticsInsight = apps.get_model("analytics", "Insight")

    to_create = []

    for alert in AlertInsight.objects.select_related(
        "metric_snapshot",
        "metric_snapshot__integration",
    ).all():
        to_create.append(
            AnalyticsInsight(
                integration=alert.metric_snapshot.integration,
                metric_snapshot=alert.metric_snapshot,
                type="snapshot_summary",
                severity="info",
                message=alert.summary,
                recommendation="Monitor performance",
                created_at=alert.created_at,
            )
        )

    if to_create:
        AnalyticsInsight.objects.bulk_create(to_create)


def backwards(apps, schema_editor):
    # No reverse migration: keep analytics insights.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("analytics", "0002_insight_metric_snapshot"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
