# Generated by Codex on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_move_insights_to_analytics"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Insight",
        ),
    ]
